name: Bazel Tests (practice itemes)

# トリガーの設定
on:
  push:  # すべてのブランチでpushされた場合
    branches:
      - '**'  # すべてのブランチ

# ジョブの設定
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Ubuntu環境で実行

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
      
      # カレントディレクトリの表示
      - name: Print Current Directory
        run: pwd

      # 必要な依存関係をインストール（Bazelのセットアップなど）
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bazel

      # テストの実行
      - name: Run Bazel Tests
        run: |
          cd ./practice_items/bazel_gtest
          bazel test //cpp_bazel_gtest.proj/test:test_lib_calc_add --test_output=all
        #continue-on-error: true  # エラーがあってもジョブ全体を失敗としない場合に有効化
